name = "VectorSphericalHarmonics"
uuid = "4b2bd704-7189-418b-a6ce-5ef15384b069"
authors = ["jishnub <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
